---
- hosts: Jenkinclient
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no

  tasks:
  - name: Copy the file from server machine to client machine.
    copy:
       src: PingAccess.yml
       dest: /sindhu

  - pause: seconds=35
...
