---
- hosts: "Jenkinclient"
  gather_facts: false
  vars_files:
     - variable.yaml
  tasks:
   - name: Copy the file from server machine to client machine.
     copy:
        src: "{{pasrcfile}}"
        dest: "{{clientsoft}}"
   - name: Install Ping Access
     shell: cd {{paclientsoft}}/ ; unzip {{pazipfile}} ; mv {{paclientsoft}}/{{pafoldername}} {{paclientprog}} ;
     become: yes
     become_method: sudo
   - name: copy the Licence file
     shell: cd {{paclientsoft}}/ ; cp -R pingaccess.lic  {{paclientprog}}/conf/ ;
   - name: Create a Service for PingAccess
     shell: cd /var/run/ ; mkdir pingaccess ; chmod -R 777 pingaccess ; cp -R  {{ paclientprog }}/sbin/linux/pingaccess /etc/init.d/ ; cd /etc/init.d/ ; cd /etc/init.d/ ; chkconfig --add pingaccess ; chmod +x pingaccess ;
   - name: Set the Environement variable
     shell: cd /etc/init.d/ ; sed -i 's/JAVA_HOME=\$JAVA_HOME/JAVA_HOME={{jdkpath2}}/g' /etc/init.d/pingaccess ; sed -i 's/PA_HOME=\$PA_HOME/PA_HOME={{paclientprog2}}/g' /etc/init.d/pingaccess ; 
   - name: Start the PingAccess
     shell: cd {{ paclientprog }}/bin/ ; nohup ./run.sh &  
   - pause: seconds=50
   ...
